services:
  renamarr:
    container_name: renamarr
    image: ghcr.io/hollanbm/renamarr:latest@sha256:2e9ea61020162b7b23cb864aa63a148ae496661942709da535e83f182734107c
    # user: 1000:1000 # if using the log_to_file feature, recommended to set the container user to match the host user to avoid permission issues with log files.
    restart: unless-stopped
    volumes:
      - ./config.yml:/config/config.yml:ro
      # - ./logs:/logs:rw # If using the log_to_file option, uncomment this line to persist logs to the host machine. **Don't forget to create logs folder first**
