repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.2
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: local
    hooks:
    - id: pytest
      name: pytest
      entry: poetry run pytest --cov=src --cov-branch tests
      language: system
      types: [python]
      pass_filenames: false
      always_run: true
