repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.15.7
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.10.11
    hooks:
      - id: uv-lock
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run --frozen --group test pytest --cov=src --cov-branch tests
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
