services:
  renamarr:
    container_name: renamarr
    image: renamarr:${BRANCH_NAME:-local}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      LOG_LEVEL: DEBUG
    restart: "no"
    volumes:
      - ./config/config.yml:/config/config.yml:ro
      - ./logs:/logs:rw
