services:
  renamarr:
    container_name: renamarr
    image: renamarr:${BRANCH_NAME:-local}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      LOG_LEVEL: DEBUG
    read_only: true  # Restrict writes to explicit mounts.
    restart: 'no'
    tmpfs:
      - /tmp  # Required for the heartbeat with read_only enabled.
    volumes:
      - ./config/config.yml:/config/config.yml:ro
      - ./logs:/logs:rw
