format = "columns"
check_uv_tool = true
check_uv_secure = true

[vulnerability_criteria]
show_severity = true
ignore_unfixed = true

[maintainability_criteria]
check_direct_dependencies_only = true
max_package_age = "P1000D"
forbid_archived = true
forbid_deprecated = true
forbid_quarantined = true
forbid_yanked = true
