name: Linters

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7

      - uses: jdx/mise-action@v4
        with:
          version: 2026.8.2
      - name: Run hadolint
        run: uv run hadolint --config .hadolint.yaml Dockerfile

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7

      - uses: jdx/mise-action@v4
        with:
          version: 2026.8.2
      - name: Run actionlint
        run: actionlint
